### ISSUE TITLE
missing training/test data

### ISSUE THREAD

**Issue by berlinguyinca** [pnnl/darkchem#1]
hi great work,

I noticed there doesn't seem to be any training/test data included as well as missing some example files. Could these be added, to dig more into this utility?

kind regards,

Gert

**Comment by smcolby** [comment]
To discuss training/test data sharing, please contact us via [email](https://biology.pnnl.gov/people/sean-colby). Regarding the missing example files, could you provide more details on exactly what you are not able to find?
